export interface Ingredient {
  name: string
  amount: number
  unit: string
}

export interface Recipe {
  id: string
  name: string
  description: string
  category: 'Accommodation & Farm' | 'Kitchen' | 'Office'
  baseServings: number
  servingUnit: string   // 'portions' | 'loaves' | 'jars' | 'slices' …
  prepTime: number      // minutes
  cookTime: number      // minutes
  ingredients: Ingredient[]
  steps: string[]
  linkedTasks?: string[]  // task.name values that link here
  tags?: string[]
}

export const DEFAULT_RECIPES: Recipe[] = [
  // ── Bakery ────────────────────────────────────────────────────────────────────
  {
    id: 'sourdough-bread',
    name: 'Sourdough Bread',
    description: 'House-baked sourdough using our own yeast culture. Prove overnight for best flavour.',
    category: 'Kitchen',
    baseServings: 1,
    servingUnit: 'loaf',
    prepTime: 30,
    cookTime: 45,
    linkedTasks: ['Prep for next day / Yeast refill', 'Kitchen prep / dough / seasoning / restock'],
    tags: ['Bakery', 'Daily'],
    ingredients: [
      { name: 'Bread flour',               amount: 500,  unit: 'g'  },
      { name: 'Active sourdough starter',  amount: 150,  unit: 'g'  },
      { name: 'Water (lukewarm 30°C)',      amount: 350,  unit: 'ml' },
      { name: 'Salt',                       amount: 10,   unit: 'g'  },
    ],
    steps: [
      'Mix flour and water together — rest 30 min (autolyse)',
      'Add starter and salt — fold to combine',
      'Stretch and fold every 30 min × 4 sets over 2 hours (bulk ferment at room temp)',
      'Shape into a round loaf — place in floured banneton seam-side up',
      'Cover and refrigerate overnight (8–12 hours)',
      'Preheat oven to 250°C with Dutch oven inside for 30 min',
      'Invert dough onto parchment — score the top with a lame or sharp knife',
      'Bake covered in Dutch oven for 20 min',
      'Remove lid — bake 20–25 min more until deep brown crust',
      'Cool on wire rack at least 1 hour before slicing',
    ],
  },

  // ── Dairy / Ferments ──────────────────────────────────────────────────────────
  {
    id: 'tofu',
    name: 'House Tofu',
    description: 'Fresh soft tofu made from local soybeans. Best served the same day.',
    category: 'Kitchen',
    baseServings: 4,
    servingUnit: 'portions',
    prepTime: 20,
    cookTime: 30,
    linkedTasks: ['Cook Yeast, Tomatoes, Yogurt, Cheese'],
    tags: ['Ferment', 'Protein'],
    ingredients: [
      { name: 'Dried soybeans',           amount: 200, unit: 'g'  },
      { name: 'Water (for soaking)',       amount: 600, unit: 'ml' },
      { name: 'Water (for blending)',      amount: 1200, unit: 'ml' },
      { name: 'Nigari (coagulant)',        amount: 4,   unit: 'g'  },
      { name: 'Cold water (for nigari)',   amount: 50,  unit: 'ml' },
    ],
    steps: [
      'Soak soybeans overnight (8–12 hours) — drain and rinse',
      'Blend soaked beans with 1200 ml fresh water until smooth',
      'Pour through cheesecloth — squeeze well to extract all soy milk',
      'Heat soy milk in pot to 85°C, stirring constantly to prevent scorching',
      'Dissolve nigari in 50 ml cold water',
      'Remove soy milk from heat — gently stir in nigari solution once',
      'Cover and rest undisturbed 10–15 min until curds form',
      'Ladle curds into tofu mould lined with cheesecloth',
      'Press with a light weight (about 500 g) for 20–30 min for soft tofu',
      'Submerge finished block in cold water — refrigerate until service',
    ],
  },
  {
    id: 'ricotta',
    name: 'Fresh Ricotta',
    description: 'Simple whole-milk ricotta. Ready in under an hour, pairs with toast and salads.',
    category: 'Kitchen',
    baseServings: 4,
    servingUnit: 'portions',
    prepTime: 5,
    cookTime: 20,
    linkedTasks: ['Cook Yeast, Tomatoes, Yogurt, Cheese'],
    tags: ['Dairy', 'Ferment'],
    ingredients: [
      { name: 'Whole milk',        amount: 1000, unit: 'ml' },
      { name: 'Fresh lemon juice', amount: 30,   unit: 'ml' },
      { name: 'White vinegar',     amount: 15,   unit: 'ml' },
      { name: 'Salt',              amount: 3,    unit: 'g'  },
    ],
    steps: [
      'Heat milk in heavy-bottomed pot over medium heat to 88°C',
      'Add lemon juice and vinegar — stir gently once only',
      'Remove from heat immediately — do NOT stir further',
      'Let rest 5 min until curds separate from whey',
      'Line a colander with muslin cloth — ladle curds in gently',
      'Drain 10–20 min (longer = firmer texture)',
      'Season with salt — use immediately or refrigerate up to 3 days',
    ],
  },
  {
    id: 'yogurt',
    name: 'Homemade Yogurt',
    description: 'Fermented overnight with live culture. Set the evening before service.',
    category: 'Kitchen',
    baseServings: 8,
    servingUnit: 'portions',
    prepTime: 10,
    cookTime: 10,
    linkedTasks: ['Cook Yeast, Tomatoes, Yogurt, Cheese'],
    tags: ['Dairy', 'Ferment'],
    ingredients: [
      { name: 'Whole milk',                    amount: 1000, unit: 'ml' },
      { name: 'Live yogurt starter (prev. batch)', amount: 60, unit: 'g' },
    ],
    steps: [
      'Heat milk in pot to 85°C — stir to prevent scorching',
      'Remove from heat — cool to 43°C (feels warm but not hot on the inside wrist)',
      'Whisk yogurt starter into warm milk until smooth and fully combined',
      'Pour into sterilised jars or container',
      'Incubate at 40–43°C — wrap in towel or place in switched-off oven with just the light on',
      'Leave undisturbed 6–8 hours or overnight',
      'Check set — should be firm and smell tangy',
      'Refrigerate immediately — keeps up to 7 days',
      'Reserve 60 g from this batch as starter for the next one',
    ],
  },
  {
    id: 'tomato-sauce',
    name: 'House Tomato Sauce',
    description: 'Slow-cooked from garden tomatoes. Base sauce for pizza, pasta, and shakshuka.',
    category: 'Kitchen',
    baseServings: 8,
    servingUnit: 'portions',
    prepTime: 20,
    cookTime: 120,
    linkedTasks: ['Cook Yeast, Tomatoes, Yogurt, Cheese'],
    tags: ['Sauce', 'Weekly batch'],
    ingredients: [
      { name: 'Fresh tomatoes',            amount: 1500, unit: 'g'  },
      { name: 'Garlic cloves',             amount: 6,    unit: 'pcs'},
      { name: 'Olive oil',                 amount: 60,   unit: 'ml' },
      { name: 'Fresh basil',               amount: 20,   unit: 'g'  },
      { name: 'Salt',                      amount: 8,    unit: 'g'  },
      { name: 'Black pepper',              amount: 3,    unit: 'g'  },
      { name: 'Sugar (balance acidity)',   amount: 10,   unit: 'g'  },
    ],
    steps: [
      'Score an X on the base of each tomato — blanch 30 sec in boiling water',
      'Transfer to ice bath immediately — peel skins off',
      'Crush garlic cloves — sauté in olive oil over medium heat until golden (not brown)',
      'Add peeled tomatoes — crush roughly with wooden spoon',
      'Bring to gentle boil — reduce heat to lowest setting',
      'Simmer uncovered 1.5–2 hours, stirring every 30 min',
      'Season with salt, pepper, and sugar — taste and adjust',
      'Tear in fresh basil — simmer 5 more minutes',
      'Cool — store in labelled containers in fridge up to 5 days, or freeze',
    ],
  },

  // ── Salads ────────────────────────────────────────────────────────────────────
  {
    id: 'green-salad',
    name: 'Garden Green Salad',
    description: 'Fresh from today\'s harvest. Adjust ingredients based on what\'s available.',
    category: 'Kitchen',
    baseServings: 4,
    servingUnit: 'portions',
    prepTime: 15,
    cookTime: 0,
    linkedTasks: ['Lunch service 11 AM–2 PM', 'Evening service 5–8 PM'],
    tags: ['Salad', 'Farm-to-table'],
    ingredients: [
      { name: 'Mixed salad leaves',        amount: 120, unit: 'g'  },
      { name: 'Cherry tomatoes',           amount: 80,  unit: 'g'  },
      { name: 'Cucumber',                  amount: 100, unit: 'g'  },
      { name: 'Red onion',                 amount: 40,  unit: 'g'  },
      { name: 'Fresh herbs (basil / mint)',amount: 20,  unit: 'g'  },
      { name: 'Olive oil',                 amount: 40,  unit: 'ml' },
      { name: 'Fresh lemon juice',         amount: 20,  unit: 'ml' },
      { name: 'Salt',                      amount: 2,   unit: 'g'  },
      { name: 'Black pepper',              amount: 1,   unit: 'g'  },
    ],
    steps: [
      'Wash all leaves and spin dry thoroughly — wet leaves dilute dressing',
      'Halve cherry tomatoes — slice cucumber into half-moons about 5 mm thick',
      'Slice red onion very thinly — soak in cold water 5 min to reduce sharpness, then drain',
      'Pick herb leaves — tear large ones by hand',
      'Whisk olive oil, lemon juice, salt, and pepper together',
      'Combine all vegetables in a large bowl',
      'Toss with dressing just before service — never dress ahead',
      'Scatter fresh herbs on top — serve immediately',
    ],
  },
  {
    id: 'tropical-salad',
    name: 'Tropical Salad',
    description: 'Sweet and tangy salad with local fruit. Great alongside tofu and rice.',
    category: 'Kitchen',
    baseServings: 4,
    servingUnit: 'portions',
    prepTime: 20,
    cookTime: 0,
    linkedTasks: ['Lunch service 11 AM–2 PM'],
    tags: ['Salad', 'Thai'],
    ingredients: [
      { name: 'Green papaya (shredded)',   amount: 200, unit: 'g'  },
      { name: 'Mango (semi-ripe, sliced)', amount: 160, unit: 'g'  },
      { name: 'Cherry tomatoes',           amount: 80,  unit: 'g'  },
      { name: 'Carrot (shredded)',         amount: 80,  unit: 'g'  },
      { name: 'Fresh lime juice',          amount: 30,  unit: 'ml' },
      { name: 'Fish sauce (or soy sauce)', amount: 20,  unit: 'ml' },
      { name: 'Palm sugar',                amount: 15,  unit: 'g'  },
      { name: 'Dried chilli flakes',       amount: 2,   unit: 'g'  },
      { name: 'Roasted peanuts',           amount: 30,  unit: 'g'  },
      { name: 'Fresh coriander',           amount: 10,  unit: 'g'  },
    ],
    steps: [
      'Shred green papaya and carrot using a julienne peeler or box grater',
      'Halve cherry tomatoes — slice mango into thin strips',
      'Combine lime juice, fish sauce, palm sugar, and chilli — stir until sugar dissolves',
      'Taste dressing — should be sour, salty, sweet, spicy in balance',
      'Toss papaya, carrot, mango, and tomatoes with dressing',
      'Plate and top with peanuts and fresh coriander',
      'Serve within 30 min — dressing wilts the papaya over time',
    ],
  },
  {
    id: 'almond-salad',
    name: 'Alumi Salad',
    description: 'Grain and almond salad with roasted vegetables. Hearty and filling.',
    category: 'Kitchen',
    baseServings: 4,
    servingUnit: 'portions',
    prepTime: 20,
    cookTime: 25,
    linkedTasks: ['Lunch service 11 AM–2 PM'],
    tags: ['Salad', 'Hearty'],
    ingredients: [
      { name: 'Cooked quinoa or brown rice', amount: 300, unit: 'g'  },
      { name: 'Sliced almonds (toasted)',    amount: 60,  unit: 'g'  },
      { name: 'Roasted pumpkin (cubed)',     amount: 200, unit: 'g'  },
      { name: 'Baby spinach',                amount: 80,  unit: 'g'  },
      { name: 'Dried cranberries',           amount: 40,  unit: 'g'  },
      { name: 'Feta or ricotta',             amount: 80,  unit: 'g'  },
      { name: 'Olive oil',                   amount: 40,  unit: 'ml' },
      { name: 'Apple cider vinegar',         amount: 20,  unit: 'ml' },
      { name: 'Honey',                       amount: 15,  unit: 'ml' },
      { name: 'Dijon mustard',               amount: 10,  unit: 'g'  },
      { name: 'Salt & pepper',               amount: 3,   unit: 'g'  },
    ],
    steps: [
      'Toss pumpkin cubes in olive oil and salt — roast at 200°C for 20–25 min until golden',
      'Toast almonds in a dry pan over medium heat until lightly golden — watch closely',
      'Whisk olive oil, apple cider vinegar, honey, and mustard into a dressing',
      'Combine warm quinoa/rice with spinach — heat gently wilts the spinach',
      'Add roasted pumpkin, cranberries, and toasted almonds',
      'Drizzle dressing and toss gently',
      'Crumble cheese on top — serve warm or at room temperature',
    ],
  },

  // ── Dessert ───────────────────────────────────────────────────────────────────
  {
    id: 'brigadeiro-cake',
    name: 'Brigadeiro Cake',
    description: 'Brazilian chocolate fudge cake beloved by guests. Prepare a day ahead for best texture.',
    category: 'Kitchen',
    baseServings: 8,
    servingUnit: 'slices',
    prepTime: 30,
    cookTime: 40,
    linkedTasks: ['Kitchen prep / dough / seasoning / restock'],
    tags: ['Dessert', 'Signature'],
    ingredients: [
      { name: 'All-purpose flour',        amount: 200, unit: 'g'  },
      { name: 'Cocoa powder (cake)',       amount: 50,  unit: 'g'  },
      { name: 'Sugar',                    amount: 200, unit: 'g'  },
      { name: 'Eggs',                     amount: 3,   unit: 'pcs'},
      { name: 'Unsalted butter',          amount: 100, unit: 'g'  },
      { name: 'Whole milk',               amount: 200, unit: 'ml' },
      { name: 'Baking powder',            amount: 8,   unit: 'g'  },
      { name: '— Brigadeiro filling —',   amount: 0,   unit: ''   },
      { name: 'Condensed milk',           amount: 395, unit: 'g'  },
      { name: 'Cocoa powder (filling)',   amount: 30,  unit: 'g'  },
      { name: 'Butter (filling)',         amount: 20,  unit: 'g'  },
      { name: 'Chocolate sprinkles',      amount: 50,  unit: 'g'  },
    ],
    steps: [
      'Preheat oven to 180°C — grease and flour a 20 cm round tin',
      'Beat butter and sugar until pale and fluffy (3–4 min)',
      'Add eggs one at a time — beat well after each addition',
      'Sift in flour, cocoa, and baking powder — fold gently',
      'Add milk — mix until smooth batter, do not over-mix',
      'Bake 30–35 min — test with skewer (comes out clean when done)',
      'Cool cake completely before filling',
      'Brigadeiro: combine condensed milk, cocoa, and butter in heavy pan',
      'Cook over low heat, stirring constantly, until very thick and pulls away from pan (12–15 min)',
      'Cool brigadeiro to room temperature before spreading',
      'Slice cake in half horizontally — spread brigadeiro generously between layers',
      'Coat top and sides with brigadeiro — press sprinkles to coat fully',
      'Refrigerate at least 2 hours before slicing — overnight is best',
    ],
  },

  // ── Drinks ────────────────────────────────────────────────────────────────────
  {
    id: 'fruits-bowl',
    name: 'Seasonal Fruits Bowl',
    description: 'Fresh fruit from the farm and local market. Vary with what\'s in season.',
    category: 'Kitchen',
    baseServings: 4,
    servingUnit: 'bowls',
    prepTime: 15,
    cookTime: 0,
    linkedTasks: ['Lunch service 11 AM–2 PM', 'Kitchen prep / dough / seasoning / restock'],
    tags: ['Fresh', 'Breakfast'],
    ingredients: [
      { name: 'Watermelon',     amount: 300, unit: 'g'  },
      { name: 'Papaya',         amount: 200, unit: 'g'  },
      { name: 'Banana',         amount: 120, unit: 'g'  },
      { name: 'Mango',          amount: 160, unit: 'g'  },
      { name: 'Fresh lime juice',amount: 20, unit: 'ml' },
      { name: 'Fresh mint',     amount: 8,   unit: 'g'  },
      { name: 'Honey (optional)',amount: 20, unit: 'ml' },
    ],
    steps: [
      'Wash all fruit thoroughly under cold water',
      'Cut watermelon into 2–3 cm cubes — remove any seeds',
      'Peel and cube papaya and mango into bite-size pieces',
      'Slice banana at an angle just before serving to prevent browning',
      'Gently toss all fruit with lime juice',
      'Drizzle honey if fruit is under-ripe or not sweet enough',
      'Garnish with fresh mint leaves — serve immediately',
    ],
  },
  {
    id: 'herbal-tea',
    name: 'House Herbal Tea',
    description: 'Farm-grown herbs brewed fresh. Offer a choice of blends to guests.',
    category: 'Kitchen',
    baseServings: 4,
    servingUnit: 'cups',
    prepTime: 5,
    cookTime: 10,
    linkedTasks: ['Evening service 5–8 PM', 'Lunch service 11 AM–2 PM'],
    tags: ['Drinks', 'Farm'],
    ingredients: [
      { name: 'Fresh lemongrass (chopped)',amount: 30,  unit: 'g'  },
      { name: 'Fresh ginger (sliced)',     amount: 20,  unit: 'g'  },
      { name: 'Pandan leaves (tied)',      amount: 2,   unit: 'pcs'},
      { name: 'Water',                     amount: 1000, unit: 'ml' },
      { name: 'Honey or palm sugar',       amount: 40,  unit: 'g'  },
      { name: 'Fresh lime juice',          amount: 20,  unit: 'ml' },
    ],
    steps: [
      'Bruise lemongrass stalks with the back of a knife — cut into 5 cm pieces',
      'Slice ginger thinly — no need to peel if from the farm',
      'Bring water to boil — add lemongrass, ginger, and pandan',
      'Reduce heat — simmer 8–10 min',
      'Strain — stir in honey until dissolved',
      'Add lime juice — taste and adjust sweetness',
      'Serve hot in small cups, or cool and serve over ice',
    ],
  },
]
